# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration for Maven
  - package-ecosystem: "maven" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    target-branch: "master"
    groups:
      jakarta:
        patterns:
        - "jakarta.*"
        update-types:
        - "patch"
      microprofile:
        patterns:
        - "org.eclipse.microprofile*"
        update-types:
        - "patch"
      fish:
        patterns:
        - "fish.payara.*"
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "jakarta.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "jakarta.*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: org.eclipse.microprofile*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.eclipse.microprofile*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "fish.payara.*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
    - dependency-name: "*"
    target-branch: "master"
